name: Milestone Version Increment
description: Increment the latest tag and create milestone using semver
author: Abhishek Bansal

branding:
  icon: tag
  color: blue

inputs:
  increment-type:
    description: Provide increment type [patch, minor, major]
    required: false
    default: patch
  increment:
    description: Provide increment value
    required: false
    default: '1'
  prefix:
    description: Provide prefix used for milestone title
    required: false
    default: ''
  due-date:
    description: Provide due date for milestone
    required: false
    default: ''
  due-day-increment:
    description: Provide number of days to add in current day for due date
    required: false
    default: ''
  description:
    description: Provide description for milestone
    default: ''
    required: false

outputs:
  title:
    description: Title of milestone with prefix
    value: ${{ steps.title.outputs.milestone_title }}
  version:
    description: Version of milestone
    value: ${{ steps.title.outputs.milestone_version }}
  number:
    description: Number of milestone
    value: ${{ steps.milestone.outputs.number }}

runs:
  using: composite
  steps:
    - name: Fetch tag and create milestone title
      id: title
      run: ${{ github.action_path }}/version_script.sh ${{ inputs.increment-type }} ${{ inputs.increment }} ${{ inputs.prefix }}
      shell: bash

    - name: Milestone due date
      id: date
      run: |
        INC=${{ inputs.due-day-increment }}
        DUE_ON=${{ inputs.due-date }}
        if [[ $INC != '' ]]; then
          DUE_ON=$(date --iso-8601=seconds -d "+$INC days")
        fi
        echo milestone_due="$DUE_ON" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Create Milestone
      id: milestone
      uses: oinume/create-scheduled-milestone-action@v1.0.2
      with:
        title: ${{ steps.title.outputs.milestone_title }}
        state: "open"
        due_on: ${{ steps.date.outputs.milestone_due }}
        description: ${{ inputs.description }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN  }}